import { AuthProvider } from "@/components/Auth/AuthProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { DefaultHeader } from "@/components/DefaultHeader";
import { DefaultFooter } from "@/components/DefaultFooter";
import { Providers } from "@/components/Redux/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <Providers>
            <DefaultHeader></DefaultHeader>
            <div className="ml-52 mr-52">
              {children}
              <DefaultFooter></DefaultFooter>
            </div>
          </Providers>
        </body>
      </html>
    </AuthProvider>
  );
}
