import { AuthProvider } from "@/components/Auth/AuthProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { DefaultHeader } from "@/components/DefaultHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <DefaultHeader></DefaultHeader>
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
